**Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**

The multinomial Naive Bayes classifier is suitable for classification with discrete features(e.g., word counts for next classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

**Import Library**

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

**Import Dataset**

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

In [6]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [8]:
df.shape

(23486, 10)

**Missing Values**

In [9]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [10]:
df[df['Review']==""] = np.NaN

In [11]:
df['Review'].fillna("No review", inplace=True)

In [12]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [13]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**Define Target(y) and Feature(X)**

In [14]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [21]:
X = df['Review']

In [22]:
y = df['Rating']

In [23]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Train Test Split**

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y, random_state=2529)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Conversion to Tokens**

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)

In [29]:
X_train = cv.fit_transform(X_train)

In [30]:
cv.get_feature_names_out()

array(['00 big', '00 fits', '00 petite', ..., 'zipper zip',
       'zippered pockets', 'zippers buttons'], dtype=object)

In [31]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
X_test = cv.fit_transform(X_test)

In [33]:
cv.get_feature_names_out()

array(['00 24', '00 petite', '00 sold', ..., 'zipper split',
       'zipper sturdy', 'zippers buttons'], dtype=object)

In [34]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Get Model Train**

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
model = MultinomialNB()

In [37]:
model.fit(X_train, y_train)

MultinomialNB()

**Get Model Prediction**

In [38]:
y_pred = model.predict(X_test)

In [39]:
y_pred.shape

(7046,)

In [40]:
y_pred

array([3, 1, 5, ..., 4, 3, 5])

**Get Probability of Each Predicted Class**

In [41]:
model.predict_proba(X_test)

array([[0.30054024, 0.10837343, 0.58677454, 0.00153512, 0.00277667],
       [0.59880251, 0.05822465, 0.31710713, 0.01311846, 0.01274724],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.07827013, 0.03410545, 0.02146026, 0.85936896, 0.0067952 ],
       [0.15524211, 0.06219954, 0.69459173, 0.00258924, 0.08537738],
       [0.40489845, 0.01153522, 0.02952864, 0.01927426, 0.53476342]])

**Get Model evaluation**

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

In [43]:
print(confusion_matrix(y_test, y_pred))

[[  77   48   37   39   52]
 [ 146   82   76   73   93]
 [ 294  172  124  105  166]
 [ 578  282  217  179  267]
 [1328  739  581  496  795]]


In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.03      0.30      0.06       253
           2       0.06      0.17      0.09       470
           3       0.12      0.14      0.13       861
           4       0.20      0.12      0.15      1523
           5       0.58      0.20      0.30      3939

    accuracy                           0.18      7046
   macro avg       0.20      0.19      0.15      7046
weighted avg       0.39      0.18      0.22      7046



**Recategories Ratings as Poor (0) and Good (1)**

In [45]:
df["Rating"].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [46]:
df.replace({'Rating': { 1:0, 2:0, 3:0, 4:1, 5:1 }}, inplace=True)

In [47]:
y = df['Rating']

In [48]:
x = df['Review']

**Train Test Split**

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y, random_state=2529)

In [51]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Conversion to Tokens**

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)

In [54]:
X_train = cv.fit_transform(X_train)

In [55]:
X_test = cv.fit_transform(X_test)

**Get Model Re-Train**

In [56]:
from sklearn.naive_bayes import MultinomialNB

In [57]:
model = MultinomialNB()

In [58]:
model.fit(X_train, y_train)

MultinomialNB()

**Get Model Prediction**

In [59]:
y_pred = model.predict(X_test)

In [60]:
y_pred.shape

(7046,)

In [61]:
y_pred

array([1, 0, 0, ..., 1, 1, 0])

**Get Model Evaluation**

In [62]:
from sklearn.metrics import confusion_matrix, classification_report

In [63]:
print(confusion_matrix(y_test, y_pred))

[[ 758  825]
 [2714 2749]]


In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.22      0.48      0.30      1583
           1       0.77      0.50      0.61      5463

    accuracy                           0.50      7046
   macro avg       0.49      0.49      0.45      7046
weighted avg       0.65      0.50      0.54      7046

